accounts/urls.py
"""Defines the url patterns for accounts"""

#Include for modules that Django has predefined
from django.urls import path, include 

app_name = 'accounts'
urlpatterns = [
    #include default auth urls. 
    path('', include('django.contrib.auth.urls')),
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs"""

from django.urls import path #This library is useful to mapping urls with the views. 
from . import views

app_name = 'learning_logs'
urlpatterns = [
    #Home page
    path('', views.index, name = 'index'),
    #Page that shows all Topics
    path('topics/', views.topics, name = 'topics'),
    #Detail page for a single topic
    path('topics/<int:topic_id>/', views.topic, name = 'topic'),
    #Page for adding a new topic. 
    path('new_topic/', views.new_topic, name = 'new_topic'),
    #Page for adding a new entry.
    path('new_entry/<int:topic_id>/', views.new_entry, name = 'new_entry'),
    #Page for editing an Entry. 
    path('edit_entry/<int:entry_id>/', views.edit_entry, name = 'edit_entry')

]

ll_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('learning_logs.urls')), 
    
]

accounts/models.py
from django.db import models

# Create your models here.

learning_logs/models.py
from django.db import models

# Create your models here.


class Topic(models.Model):
    """A topic the user is learning about"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        """Return a string representation of the model"""
        return self.text
    

class Entry(models.Model):
    """This is the code that connects each entry to a specific topic"""
    """Something specific learning about a topic"""
    topic = models.ForeignKey(Topic, on_delete = models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self): ##How the admin user will represent a string. 
        """Return a simple string representing the entry"""
        return f"{self.text[:50]}..."

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    """Meta class is an inner class you put inside your models or forms to provide 
    metadata, basically configuration options that describe the behavior of the model
    or form without being a database field itself. 
    Here are some extra instructions about how to handle this model."""
    class Meta:
        model = Topic
        #fields = ['text']
        fields = '__all__'
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text'] #Show the text item 
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

accounts/views.py
from django.shortcuts import render

# Create your views here.

learning_logs/views.py
#Render the response based on the data provided by views 
from django.shortcuts import render, redirect

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.
"""A view function takes in information from a request, prepares the data needed to generate a page, 
and then sends the data back to the browser. """

def index(request):
    """The home page for learning log"""
    return render(request, 'learning_logs/index.html')


def topics(request):
    """Show all topics"""
    topics = Topic.objects.order_by("date_added")
    context = {"topics": topics}
    return render(request, 'learning_logs/topics.html', context)

def topic(request, topic_id):
    """Show a single topic and all it entries."""
    topic = Topic.objects.get(id = topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


def new_topic(request):
    """Add a nre topic."""
    if request.method != 'POST':
        #No data submitted; create a blank form. 
        form = TopicForm()
    else:
        #POST data submitted; process data.
        form = TopicForm(data = request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topics')
        
        #Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


def new_entry(request, topic_id):
    """Add a new entry for a partiular Topic"""
    topic = Topic.objects.get(id = topic_id)

    if request.method != 'POST':
        #No data submitted; create a blank form. 
        form = EntryForm()
    
    else:
        #POST data submitted; process data. 
        form = EntryForm(data= request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id = topic_id)
        
    #Display a blank or invalid form.
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if request.method != 'POST':
        #INitial reques; pre-filll form with the current entry. 
        form = EntryForm(instance=entry)

    else:
        #POST data sumitted; process data. 
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id = topic.id)
    
    context = {'entry': entry, 'topic':topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

learning_logs/templates/learning_logs/base.html
<p>
    <a href="{% url 'learning_logs:index' %}">learning log </a> - <!-- href create a clickable buttom to the index.tml -->
    <a href="{% url 'learning_logs:topics' %}">topic</a> - <!-- href create a clickable buttom to the index.tml -->
    {% if 'user.is_authenticated' %}
        Hello , {{user.username}}.
    {% else %}
        <a href = "{% url 'accounts:login' %}"> Log in</a>
    {% endif %}

</p>
{% block content %}{% endblock content %} 
<!-- Used to a new template, it may use it or not to write new content. is a placeholder the child template
    will define the kind of information that goes in the content block-->

{% if user.is_authenticated %}
    <hr />
    <form action="{% url 'accounts:logout' %}" method='post'>
        {% csfr_token %}
        <buttom name = 'submit'> Log out</button>
    </form>
{% endif %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}

{% block content %}
    <p><a href = "{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></p>

    <p>Edit Entry:</p>

    <form action = "{% url 'learning_logs:edit_entry' entry.id %}" method = 'post'>
        {% csrf_token%}
        {{ form.as_div }}
        <button name = "submit"> Save Changes</button>
    </form>

{% endblock content%}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}

{% block content %}
<p> Learning log helps you keep track in your learning, for any topic you're interested in.</p>
{% endblock content%}

<!-- Everything that we aren't inheriting from the parent template goes inside the content block. -->

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}

{% block content %}
    <p><a href= "{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

    <p>Add a new entry:</p>
    <form action = "{% url 'learning_logs:new_entry' topic.id %}" method = 'post'>
        {% csrf_token%}
        {{ form.as_div}}
        <button name = "submit"> Add Entry</button>
    </form>
{% endblock content%}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}
    <p>Add a new Topic </p>

    <form action = "{% url 'learning_logs:new_topic' %}" method = 'post'>
        {% csrf_token%}
        {{ form.as_div}}
        <button name = "submit"> Add topic</button>
    </form>

{% endblock content%}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}

<p> Topic: {{ topic.text }}</p>

<p>Entries:</p>
<p>
    <a href = "{% url 'learning_logs:new_entry' topic.id %}">Add a new entry</a>
</p>

<ul>
    {% for entry in entries %}
    <li>
        <p>{{ entry.date_added|date:'M d, Y H:i'}}</p>
        <p>{{ entry.text|linebreaks }}</p>
        <p>
            <a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit Entry</a>    
        </p>
    </li>
    {%empty%}

    <li>There are no entries for this topic yet. </li>
    {% endfor %}
</ul>

{% endblock content%}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block content %}
<p> Topics </p>
<ul>
    {% for topic in topics %}
        <li>
            <a href="{% url 'learning_logs:topic' topic.id %}">
                {{ topic.text }}</a>
        </lli>
    {% empty %}
        <li>No topics have been added yet. </li>
    {% endfor %}
        </ul>
    <a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>
{% endblock content %} 